In [2]:
import pandas as pd
import numpy as np

In [2]:
import os
os.getcwd()

'/Users/kt/Documents/UBC_MDS/block4/553/553proj/553project'

In [198]:
# first set of labels
labels1 = pd.read_csv('dataset3_labelled.csv')
ratings1 = labels1[['processed_text', 'Rating', 'User Experience', 'Bug Report', 'Feature Report']]

In [182]:
# second set of labels
labels2 = pd.read_csv('Dataset3 labelled.csv')
labels2.head()

,appTitle,userName,date,score,Category,date_ex,processed_text,wordcount,label
0,Helix Jump,wan husna,14-Apr-19,5,GAME_ACTION,4/14/2019,A great game to be during times Nice,8,rating
1,Pandora Music,taja sims,13-Mar-19,5,MUSIC_AND_AUDIO,4/1/2019,I truly love pandora,4,rating
2,Lose Belly Fat in 30 Days - Flat Stomach,NaN,15-Dec-18,5,HEALTH_AND_FITNESS,3/24/2019,I need all the help I need 5ft and I need to l...,28,user experience
3,Roblox,Reece McBratney,24-Mar-19,3,FAMILY,3/24/2019,it s not great but it s good,8,rating
4,ABCmouse.com,A Google User,22-Feb-18,5,EDUCATION,4/7/2019,I think this is cool this is learning and and ...,13,rating

In [176]:
# convert second set of labels to binary
rating = np.zeros(len(labels2))
usr_xp = np.zeros(len(labels2))
bug = np.zeros(len(labels2))
feature = np.zeros(len(labels2))


for x,i in zip(range(len(labels2)+1), labels2['label']):
    if i == 'rating':
        rating[x] = 1
    elif i == 'user experience':
        usr_xp[x] = 1
    elif i == 'feature request':
        feature[x] = 1
    elif i == 'bug report':
        bug[x] = 1
    else:
        print(labels2.iloc[x])

appTitle          Pixel Art: Color by Number, Pixel Color
userName                                  Adrian Trujillo
date                                             4-Oct-18
score                                                   3
Category                                    ENTERTAINMENT
date_ex                                          4/1/2019
processed_text                          It is a fun game
wordcount                                               5
label                                                 NaN
Name: 49, dtype: object

In [188]:
# organize and concat to original
ratings2 = pd.DataFrame({'Rating' : rating, 'User Experience' : usr_xp, 'Bug Report' : bug, 'Feature Report' : feature})
labels2 = pd.concat([labels2, ratings], axis =1, sort = False)

# only keep binary labels
labels2_2 = labels2.drop(columns = ['label'])

384

In [200]:
pd.concat([ratings1, ratings2], axis =1, sort = False).to_csv('dataset3_to_review.csv')

In [14]:
reviewed = pd.read_csv('labelled.csv')

In [15]:
reviewed

,processed_text,Rating,User Experience,Bug Report,Feature Report,label
0,A great game to be during times Nice,1,0,0,0,Rating
1,I truly love pandora,0,1,0,0,UserExperience
2,I need all the help I need 5ft and I need to l...,0,1,0,0,UserExperience
3,it s not great but it s good,1,0,0,0,Rating
4,I think this is cool this is learning and and ...,0,1,0,0,UserExperience
...,...,...,...,...,...,...
379,Really good for,1,0,0,0,Rating
380,It is my first time to use this see who it is,0,0,0,0,FALSE
381,I love it,1,0,0,0,Rating
382,fun fact it s fun,1,0,0,0,Rating
383,I dont stay in and wont work everyday I love ...,0,1,0,0,UserExperience